### ISSUE TITLE
Melhorias na documentação

### ISSUE THREAD

**Issue by orlandosaraivajr** [gustapinto/fatec_dsm_pi_terceiro_semestre#2]
Podem utilizar o pacote Diagrams ( https://diagrams.mingrammer.com/ )

**Comment by gustapinto** [comment]
Diagrama da [página de arquitetuera da wiki](https://github.com/gustapinto/fatec_dsm_pi_terceiro_semestre/wiki/Arquitetura) gerado usando o diagrams!
